{
 "title": "Gitlab Runner Metrics",
 "description": "Metrics from gitlab runners",
 "tags": [
  "service",
  "gitlab-runner"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": {
     "query": "label_values(gitlab_runner_autoscaling_machine_states,pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "About pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "pod",
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "options": {
    "content": "<div>\n  <img style=\"height: 90%;width: 100%;display: block;margin: auto auto;\" src=\"https://gitlab.com/uploads/-/system/project/avatar/17704869/GitLabRunnerAWSASG.png\"/>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "current version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitlab_runner_version_info{pod=~\"^$pod$\"}"
    }
   ]
  },
  {
   "title": "Global concurrent jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gitlab_runner_concurrent{pod=~\"^$pod$\"}",
     "legendFormat": "Concurrent job"
    }
   ]
  },
  {
   "title": "Runner limits by token",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gitlab_runner_limit{pod=~\"^$pod$\"}",
     "legendFormat": "{{runner}}"
    }
   ]
  },
  {
   "title": "Total jobs executed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gitlab_runner_jobs_total{pod=~\"^$pod$\"}",
     "legendFormat": "{{runner}}"
    }
   ]
  },
  {
   "title": "Total failed jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(gitlab_runner_failed_jobs_total{pod=~\"^$pod$\"}) by (runner)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Executed jobs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(gitlab_runner_jobs_total{pod=~\"^$pod$\"} [1m]) ",
     "legendFormat": "{{app}} : {{runner}} "
    }
   ]
  },
  {
   "title": "Runnig jobs phase",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(gitlab_runner_jobs{state=\"running\",pod=~\"^$pod$\"}) by (pod,job,executor_stage,stage)",
     "legendFormat": "{{app}} : {{job}} : {{executor_stage}} : {{stage}} "
    }
   ]
  },
  {
   "title": "Average duration of jobs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum (rate(gitlab_runner_job_duration_seconds_sum [1m]) / rate(gitlab_runner_job_duration_seconds_count [1m])) by (pod,runner,job,)",
     "legendFormat": "{{app}} : {{runner}} : {{job}}"
    }
   ]
  },
  {
   "title": "The number of caught errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(delta(gitlab_runner_errors_total{pod=~\"^$pod$\"} [1m])) by (pod,level)",
     "legendFormat": "{{app}} : {{level}}"
    }
   ]
  },
  {
   "title": "Total number of api requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(gitlab_runner_api_request_statuses_total{pod=~\"^$pod$\"} [1m])",
     "legendFormat": "{{app}} : api {{endpoint}} : status {{status}}"
    }
   ]
  },
  {
   "title": "Concurrency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "The current number of concurrent requests for a new job",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gitlab_runner_request_concurrency{pod=~\"^$pod$\"}",
     "legendFormat": "{{app}} : {{runner}}"
    }
   ]
  },
  {
   "title": "Counter tracking exceeding of request concurrency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(gitlab_runner_request_concurrency_exceeded_total{pod=~\"^$pod$\"} [2m])",
     "legendFormat": "{{app}} : {{ runner}} "
    }
   ]
  },
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {}
   ]
  },
  {
   "title": " CPU time spent ",
   "type": "timeseries",
   "description": "(user and system)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{pod=~\"^$pod$\"} [1m]) * 100",
     "legendFormat": "{{app}} "
    }
   ]
  },
  {
   "title": "Number of open file descriptors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{pod=~\"^$pod$\"}",
     "legendFormat": "{{app}} "
    }
   ]
  },
  {
   "title": "Virtual memory size in bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{pod=~\"^$pod$\"}",
     "legendFormat": "{{app}} "
    }
   ]
  },
  {
   "title": "Resident memory size in bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{pod=~\"^$pod$\"}",
     "legendFormat": "{{app}} "
    }
   ]
  }
 ]
}